#!/usr/bin/env bash
#
# Shared utility functions for agent.manager task skills.
# Source this file at the top of any skill that works with tasks:
#
#   ROOT=$(git rev-parse --show-toplevel)
#   source "$ROOT/agents/agent.manager/scripts/task-helpers.sh"
#

set -euo pipefail

: "${ROOT:=$(git rev-parse --show-toplevel)}"
: "${MANAGER_TASKS:=$ROOT/agents/agent.manager/tasks}"
: "${TASKS_FILE:=$MANAGER_TASKS/tasks.index.jsonc}"
: "${CONFIG_PATH:=$ROOT/agents/agent.manager/config.manager.jsonc}"

# ---------------------------------------------------------------------------
# parse_jsonc FILE
#   Strips // line comments and trailing commas from a .jsonc file,
#   outputs valid JSON to stdout.
# ---------------------------------------------------------------------------
parse_jsonc() {
    local file="$1"
    if [ ! -f "$file" ]; then
        echo "[]"
        return 0
    fi
    sed -E \
        -e 's|//.*$||'             \
        -e 's/,[[:space:]]*\}/}/g' \
        -e 's/,[[:space:]]*\]/]/g' \
        "$file" \
    | grep -v '^[[:space:]]*$'     \
    | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    json.dump(data, sys.stdout, indent=4)
except json.JSONDecodeError:
    sys.stdout.write('[]')
"
}

# ---------------------------------------------------------------------------
# get_git_email
#   Outputs the current git user.email.
# ---------------------------------------------------------------------------
get_git_email() {
    git config user.email 2>/dev/null || echo ""
}

# ---------------------------------------------------------------------------
# get_git_user
#   Outputs the current git user.name.
# ---------------------------------------------------------------------------
get_git_user() {
    git config user.name 2>/dev/null || echo ""
}

# ---------------------------------------------------------------------------
# task_slug ID SCOPE TYPE
#   Outputs the canonical slug: "{ID}.{SCOPE}.{TYPE}"
#   All parts are lowercased and spaces replaced with hyphens.
# ---------------------------------------------------------------------------
task_slug() {
    local id="$1"
    local scope="$2"
    local type="$3"
    scope=$(echo "$scope" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    type=$(echo "$type" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    echo "${id}.${scope}.${type}"
}

# ---------------------------------------------------------------------------
# branch_name TYPE ID SLUG_TEXT
#   Outputs a git-safe branch name: "{type}/{id}-{slug}"
#   Example: branch_name feature 12 "user profile photo" → feature/12-user-profile-photo
# ---------------------------------------------------------------------------
branch_name() {
    local type="$1"
    local id="$2"
    local slug="$3"
    slug=$(echo "$slug" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')
    echo "${type}/${id}-${slug}"
}

# ---------------------------------------------------------------------------
# get_task ID
#   Extracts a single task object from tasks.index.jsonc by github_issue_id.
#   Outputs JSON to stdout. Returns exit code 1 if not found.
# ---------------------------------------------------------------------------
get_task() {
    local id="$1"
    local result
    result=$(parse_jsonc "$TASKS_FILE" | python3 -c "
import sys, json
tasks = json.load(sys.stdin)
for t in tasks:
    if str(t.get('github_issue_id', '')) == '$id':
        json.dump(t, sys.stdout, indent=4)
        sys.exit(0)
sys.exit(1)
" 2>/dev/null)
    if [ $? -eq 0 ]; then
        echo "$result"
        return 0
    else
        return 1
    fi
}

# ---------------------------------------------------------------------------
# create_task_folder SLUG
#   Creates the in_plan folder structure and an empty plan.md stub.
# ---------------------------------------------------------------------------
create_task_folder() {
    local slug="$1"
    local dir="$MANAGER_TASKS/in_plan/$slug"
    mkdir -p "$dir"

    if [ ! -f "$dir/plan.md" ]; then
        cat > "$dir/plan.md" <<'PLAN_STUB'
# Plan

<!-- Generated by create-task. Fill in during /create-plan or /do-task. -->

## Goal

## Sub-tasks

## Definition of Done

## Notes
PLAN_STUB
    fi
    echo "$dir"
}

# ---------------------------------------------------------------------------
# count_tasks [status_filter]
#   Counts tasks in tasks.index.jsonc, optionally filtered by status.
#   Example: count_tasks "pending"
#   No argument = count all tasks.
# ---------------------------------------------------------------------------
count_tasks() {
    local filter="${1:-}"
    parse_jsonc "$TASKS_FILE" | python3 -c "
import sys, json
tasks = json.load(sys.stdin)
status_filter = '$filter'
if status_filter:
    print(sum(1 for t in tasks if t.get('status') == status_filter))
else:
    print(len(tasks))
"
}

# ---------------------------------------------------------------------------
# derive_task_status TASK_JSON
#   Reads a single task JSON from stdin and outputs the derived status
#   based on sub-task states. Rules (checked in order):
#     1. All sub-tasks done/cancelled         → in_review (if pr_id) or done
#     2. Any sub-task in_progress             → in_progress
#     3. Any sub-task awaiting_review (none in_progress) → in_progress
#     4. All non-cancelled sub-tasks blocked  → blocked
#     5. All sub-tasks pending + plan exists  → planned
#     6. All sub-tasks pending + no plan      → pending
#   Outputs one status string to stdout.
# ---------------------------------------------------------------------------
derive_task_status() {
    python3 -c "
import sys, json

task = json.load(sys.stdin)
subs = task.get('sub_tasks', [])

if not subs:
    print(task.get('status', 'pending'))
    sys.exit(0)

statuses = [s.get('status', 'pending') for s in subs]
active = [s for s in statuses if s != 'cancelled']

if not active:
    print('cancelled')
    sys.exit(0)

if all(s in ('done', 'cancelled') for s in statuses):
    print('in_review' if task.get('pr_id') else 'done')
elif any(s == 'in_progress' for s in statuses):
    print('in_progress')
elif any(s == 'awaiting_review' for s in statuses):
    print('in_progress')
elif all(s == 'blocked' for s in active):
    print('blocked')
elif all(s == 'pending' for s in active):
    task_dir = task.get('task_directory', '')
    print('planned' if task_dir else 'pending')
else:
    print(task.get('status', 'pending'))
"
}

# ---------------------------------------------------------------------------
# today_iso
#   Outputs today's date as YYYY-MM-DD.
# ---------------------------------------------------------------------------
today_iso() {
    date +%Y-%m-%d
}
